title: Tech Write Blog
description: 기술적고민 및 해결과정의 기록
baseurl: "/techwrite"
url: "https://longvacation13.github.io"
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge

sass:
  style: compressed
